apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rwro
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rwro
    app.kubernetes.io/part-of: ci10t-777-0074-app
  name: devfile-sample-rwro
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rwro
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rwro
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0074-tenant/ci10t-777-0074-app/devfile-sample-rwro@sha256:3a51087eeb17ee5aa9131c7ed3c5c05cdd9823bdd5e5e6e5a45cc1c2a7cdf23b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
